### ISSUE TITLE
build: BridgeError assigns discriminants 41 and 42 twice, so the crate does not compile

### ISSUE THREAD

**Issue by CHEF-SAVY** [C-Address-Onboarding-Bridge/C-Address-Onboarding-Bridge--Contract#403]
## Summary

`cargo check` currently fails on `main` with two `E0081` errors:

```
error[E0081]: discriminant value `41` assigned more than once
error[E0081]: discriminant value `42` assigned more than once
```

Four variants in `BridgeError` collide in pairs:

```rust
BatchTooLarge             = 41,
InvalidAddress            = 42,
DuplicateRelayerSignature = 41,   // collides with BatchTooLarge
PoolNotWhitelisted        = 42,   // collides with InvalidAddress
```

Two separate pull requests each added error variants and each picked the next free numbers from the state of the enum on its own branch. Both compiled in isolation; the merge produced the collision. The highest discriminant currently in use is 44.

Note that fixing this alone will not make the build green — there are also four referenced-but-undeclared variants, tracked separately.

## Checklist

- [ ] Renumber `DuplicateRelayerSignature` and `PoolNotWhitelisted` to unused discriminants (45 and 46 are free)
- [ ] Do not renumber `BatchTooLarge` or `InvalidAddress` — changing an existing error's value is a breaking change for any client matching on it
- [ ] Confirm `cargo check` no longer reports either E0081
- [ ] Add a comment near the enum recording the next free discriminant, so the next contributor does not repeat the collision

## Difficulty

🟢 **Good First Issue**

**File(s):** `contracts/onboarding-bridge/src/lib.rs`

## Getting started

This is a self-contained task — no additional repo access or secrets needed.

```bash
git clone https://github.com/<your-fork>/C-Address-Onboarding-Bridge--Contract.git
cd C-Address-Onboarding-Bridge--Contract
```

Run `cargo test` from the workspace root, and `cargo build --target wasm32v1-none --release` to confirm the contract still compiles to WASM. Add a test that fails without your change.

## Submitting your PR

When you open your pull request, include `Closes #123` in the PR description (using this issue's actual number in place of 123). This links the PR to the issue and closes it automatically on merge.

Please follow this repo's branch naming and commit conventions from [CONTRIBUTING.md](CONTRIBUTING.md#branch-naming) (e.g. `fix/short-description`, `feat/short-description`).

**Comment by Netty-kun** [comment]
@Netty-kun has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> I'd like to work on this issue.. will be done within minutes or an hour tops. 


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/f89574fb-eb1a-4acd-be68-2231ea1596c8) or assign @Netty-kun to this issue.

**Comment by Muyideen-js** [comment]
@Muyideen-js has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hi, I can fix this


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/f89574fb-eb1a-4acd-be68-2231ea1596c8) or assign @Muyideen-js to this issue.

**Comment by Sulamoney222** [comment]
@Sulamoney222 has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hello Maintainer, I’ve reviewed this issue and it matches my expertise. I can deliver a clean solution that fits the requirements. Kindly assign it to me.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/f89574fb-eb1a-4acd-be68-2231ea1596c8) or assign @Sulamoney222 to this issue.

**Comment by nelly439** [comment]
@nelly439 has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> I’m a strong fit for this good-first issue because I can resolve the discriminant collision without changing any existing error values that may be relied on by clients. I’ll move the two conflicting variants to the unused values 45 and 46, add the requested documentation comment to prevent future collisions, and add a regression test covering the enum. I’ll also verify the fix with cargo check, workspace tests, and the WASM release build while keeping the scope narrowly focused.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/f89574fb-eb1a-4acd-be68-2231ea1596c8) or assign @nelly439 to this issue.

**Comment by TheFaith-Code** [comment]
@TheFaith-Code has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hi, I'd like to work on this issue.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/f89574fb-eb1a-4acd-be68-2231ea1596c8) or assign @TheFaith-Code to this issue.

**Comment by Lyonjohn** [comment]
@Lyonjohn has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



>  I’ve thoroughly reviewed the requirements and can work on fixing the issue while ensuring the implementation meets the acceptance criteria.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/f89574fb-eb1a-4acd-be68-2231ea1596c8) or assign @Lyonjohn to this issue.

**Comment by AgentX010** [comment]
@AgentX010 has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> This project aligns well with my experience. I'm confident in providing a clean, effective, and thoroughly tested solution.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/f89574fb-eb1a-4acd-be68-2231ea1596c8) or assign @AgentX010 to this issue.

**Comment by Otfrugger** [comment]
@Otfrugger has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> can i work on this asap


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/f89574fb-eb1a-4acd-be68-2231ea1596c8) or assign @Otfrugger to this issue.

**Comment by CHEF-SAVY** [comment]
Fixed in 6187eaa — `cargo check` now passes on `main`. Renumbered `DuplicateRelayerSignature` to 45 and `PoolNotWhitelisted` to 46 (leaving existing discriminants untouched), and declared the four referenced-but-missing variants. Left #405 open: nothing in CI would have caught this.
